name: guess-game

on:
  push:
    paths: 'guess-game/**'

jobs:
  tests:
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout code"
        uses: actions/checkout@v2
      - name: "setup rust version"
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.59.0
      - name: "download asser-version binary"
        run: |
          curl -Lo /tmp/assert-version https://github.com/lonepeon/cicd/releases/download/v20220315143056/assert-version-linux-386
          chmod u+x /tmp/assert-version
      - name: "assert rust version"
        run: /tm/assert-version rust
      - name: "run unit tests"
        run: make -C guess-game test-unit
      - name: "run format tests"
        run: make -C guess-game test-format
      - name: "run static-check tests"
        run: make -C guess-game test-staticcheck
